# This rule is not used by the project hcrm itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the hcloud.bunskin.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hcrm
    app.kubernetes.io/managed-by: kustomize
  name: hclouddnszone-editor-role
rules:
- apiGroups:
  - hcloud.bunskin.com
  resources:
  - hclouddnszones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hcloud.bunskin.com
  resources:
  - hclouddnszones/status
  verbs:
  - get
