# This rule is not used by the project hcrm itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over hcloud.bunskin.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: hcrm
    app.kubernetes.io/managed-by: kustomize
  name: hclouddnszone-admin-role
rules:
- apiGroups:
  - hcloud.bunskin.com
  resources:
  - hclouddnszones
  verbs:
  - '*'
- apiGroups:
  - hcloud.bunskin.com
  resources:
  - hclouddnszones/status
  verbs:
  - get
